version: "2"
services:

  rabbitmq:
      image: rabbitmq:management
      ports:
            - "15672:15672"
            - "5672:5672"
  db:
    image: postgres
    volumes:
      - postgres-db-volume:/data/pg
    ports:
      - "5432:5432"
  dbService:
    image: saas-db
    depends_on:
      - "rabbitmq"
      - "db"
      - "redis"
    links:
      - rabbitmq:rabbitmq
      - db:db
  redis:
      image: redis
  logic:
        image: saas-logic
        depends_on:
          - "rabbitmq"
          - "db"
          - "redis"
        ports:
          - "3000:3000"
        links:
          - rabbitmq:rabbitmq
volumes:
  postgres-db-volume:
